tidelift: "npm/decentralized-internet"
tidelift: "dub/decentralized-internet"
tidelift: "pub/decentralized-internet"
tidelift: "pypi/decentralized-internet"
tidelift: "atom/decentralized-internet"
open_collective: decentralized-internet
tidelift: "cargo/decentralized-internet"
tidelift: "racket/decentralized-internet"
tidelift: "rubygems/decentralized-internet"
tidelift: "puppet/gamer456148-decentralized_internet"
